version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
    - image: circleci/openjdk:8u181-jdk-node-browsers-legacy
    steps:
    - checkout
    - run: ./gradlew build deployHeroku
  deploy:
    steps:
    - checkout
    - run:
        name: Deploy Master to Heroku
        command: |
