version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk-browsers
    steps:
    - checkout
    - run: cd cicd-workshop-demo-project; chmod +x ./gradlew; ./gradlew build
workflows:
  version: 2
  build:
    jobs:
    - build