version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
    - image: circleci/openjdk:8u181-jdk-node-browsers-legacy
    steps:
    - checkout
    - run: chmod +x ./gradlew; ./gradlew build
workflows:
  version: 2
  build:
    jobs:
    - build