version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
    - image: circleci/openjdk:8u181-jdk-node-browsers-legacy
    steps:
    - checkout
    - run: ./gradlew build
  deploy:
    steps:
    - run:
        name: Deploy Master to Heroku
        command: ./gradlew deployHeroku
workflows:
  version: 2
  build:
    jobs:
    - build
    - deploy