version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8u181-jdk-node-browsers-legacy
    steps:
    - checkout
    - run: chmod +x ./gradlew && ./gradlew build
  test:
    docker:
    - image: circleci/openjdk:8u181-jdk-node-browsers-legacy
    steps:
    - checkout
    - run: ./gradlew test
workflows:
  version: 2
  build_and_test:
    jobs:
    - build
    - test